export {
  ADHKAR_REMINDER_MINUTES,
  ALARM_CHANNELS,
  BEFORE_ADHAN_MINUTES,
  IQAMAH_OFFSET_MINUTES,
  MOMENT_LABELS,
  NATIVE_SCHEDULE_DAYS,
  NOTIFICATION_COPY,
  PRAYER_LABELS,
  PRAYER_TIMES_COPY as COPY,
} from '@nabd/shared'
