export const deviceCopy = {
  actions: {
    requestNotificationPermission: 'السماح بالإشعارات',
    enableNotifications: 'تفعيل الإشعارات',
    openAppSettings: 'فتح إعدادات التطبيق',
    openExactAlarmSettings: 'فتح إعدادات المنبّهات الدقيقة',
    openLocationSettings: 'فتح إعدادات الموقع',
    retryLocation: 'إعادة محاولة تحديد الموقع',
    requestBatteryExemption: 'تفعيل حماية البطارية',
    openBatterySettings: 'فتح إعدادات البطارية',
    retryDeviceAction: 'أعد المحاولة',
  },
  errors: {
    actionFailed: 'تعذّر تنفيذ الإجراء — أعد المحاولة.',
    preferencesReadFailed: 'تعذّر تحميل إعدادات التطبيق — استُخدمت الإعدادات الافتراضية.',
    scheduleRejected: 'تعذّر تفعيل تنبيهات الصلاة — تحقّق من الإشعارات والمنبّهات الدقيقة ثم أعد المحاولة.',
  },
  settings: {
    deviceHeading: 'إعدادات الجهاز والتنبيهات',
    notificationsChecking: 'جارٍ التحقق من الإشعارات…',
    notificationsLabel: 'الإشعارات',
    notificationsEnabled: 'تنبيهات الصلاة مفعّلة',
    notificationsDisabled: 'تنبيهات الصلاة متوقفة',
    silentMode: 'التنبيه في الوضع الصامت',
    exactAlarmLabel: 'المنبّهات الدقيقة',
    exactAlarmChecking: 'جارٍ التحقق من المنبّهات الدقيقة…',
    countdownLabel: 'العدّاد الدائم',
    countdownChecking: 'جارٍ التحقق من العدّاد…',
    countdownEnabled: 'إيقاف العدّاد الدائم',
    countdownDisabled: 'تشغيل العدّاد الدائم',
    batteryLabel: 'حماية البطارية',
    batteryChecking: 'جارٍ التحقق من حماية البطارية…',
    locationLabel: 'الموقع',
    locationChecking: 'جارٍ التحقق من الموقع…',
    requestLocation: 'تحديد موقعي الآن',
    beforeAdhan: 'قبل الأذان بربع ساعة',
    atAdhan: 'عند الأذان',
    atIqamah: 'عند الإقامة',
    morningAdhkar: 'تذكير أذكار الصباح',
    eveningAdhkar: 'تذكير أذكار المساء',
    hydrationFailed: 'تعذّر تحميل إعدادات التطبيق — استُخدمت الإعدادات الافتراضية.',
    loading: 'جارٍ تحميل الإعدادات…',
  },
  notifications: {
    ready: 'الإشعارات مفعّلة.',
    disabled: 'الإشعارات متوقفة من داخل التطبيق — فعّلها للمتابعة.',
    deviceDisabled: 'إشعارات الجهاز متوقفة — فعّلها من إعدادات التطبيق.',
    permissionRequired: 'اسمح بالإشعارات لتفعيل التنبيهات والعدّاد.',
    settingsRequired: 'الإشعارات محظورة — فعّلها من إعدادات التطبيق.',
    channelsUnavailable: 'قنوات الإشعارات غير جاهزة — افتح إعدادات التطبيق وحاول مجددًا.',
    silentModeFailed:
      'تعذّر تجهيز صوت الوضع الصامت — افتح إعدادات الإشعارات؛ لا يتجاوز التطبيق وضع عدم الإزعاج.',
  },
  exactAlarm: {
    ready: 'المنبّهات الدقيقة متاحة.',
    notRequired: 'المنبّهات الدقيقة غير مطلوبة على هذا الإصدار.',
    settingsRequired: 'السماح بالمنبّهات الدقيقة مطلوب لضبط مواقيت الصلاة.',
    unavailable: 'تعذّر التحقق من المنبّهات الدقيقة — افتح إعدادات التطبيق وتحقق منها.',
  },
  location: {
    ready: 'تم تحديد الموقع.',
    offlineCache: 'لا يوجد اتصال — نستخدم آخر موقع محفوظ.',
    stale: 'الموقع المحفوظ قديم — أعد محاولة تحديد موقعك.',
    cityRequired: 'لم يُحفظ اسم المدينة — أعد تحديد موقعك لإكمال البيانات.',
    cityUnavailable: 'تم تحديد الموقع، لكن اسم المدينة غير متاح حاليًا.',
    permissionRequired: 'اسمح للتطبيق بالوصول إلى الموقع ثم أعد المحاولة.',
    settingsRequired: 'صلاحية الموقع محظورة — فعّلها من إعدادات التطبيق.',
    gpsDisabled: 'خدمة الموقع (GPS) مغلقة — فعّلها ثم أعد المحاولة.',
    noCache: 'تعذّر تحديد الموقع دون اتصال ولا يوجد موقع محفوظ.',
    unavailable: 'تعذّر الحصول على الموقع — أعد المحاولة لاحقًا.',
  },
  countdown: {
    disabled: 'العدّاد الدائم متوقف.',
    ready: 'العدّاد الدائم مفعّل.',
    notificationsRequired: 'فعّل الإشعارات لتشغيل العدّاد الدائم.',
    locationRequired: 'حدّد موقعك لتشغيل العدّاد الدائم.',
  },
  battery: {
    ready: 'حماية البطارية مفعّلة للتطبيق.',
    optimized: 'يمكن لحماية البطارية تأخير التنبيهات — التفعيل اختياري.',
    unknown: 'تعذّر التحقق من حماية البطارية — افتح إعدادات البطارية للتأكد.',
    stale: 'بيانات حماية البطارية قديمة — افتح إعدادات البطارية للتأكد.',
    unavailable: 'تعذّر فتح طلب حماية البطارية — جرّب إعدادات البطارية.',
  },
} as const
