export const STATS_COPY = {
  streakSingular: 'يوم',
  streakPlural: 'أيام',
  streakSuffix: 'متتالية',
  streakPrompt: 'أكمل وِرد اليوم لتُبقي الشعلة مشتعلة',
  completionTile: 'إتمام الوِرد — آخر شهر',
  bestStreakTile: 'أفضل سلسلة أيام مكتملة',
  todayDetail: 'اليوم بالتفصيل',
  itemStats: 'محاسبة العناصر',
  voluntary: 'تطوّع',
  optionalStats: (done: string, streak: string) => `أُدّيت ${done} — أطول تتابع ${streak}`,
  attainment: (done: string, window: string) => ` — أيام الاستهداف ${done}/${window}`,
  consecutive: 'متتالية',
  missed: 'فات',
  day: 'يوم',
  exportData: 'تصدير بياناتك:',
  exportWeek: 'أسبوع',
  exportMonth: 'شهر',
} as const
