import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { SITE_URL } from '../../../packages/shared/src/constants/site.ts'
import { themeTokens, webThemeValues } from '../../../packages/shared/src/tokens/tokens.ts'

const themeOutputPath = fileURLToPath(new URL('../src/generated-theme.css', import.meta.url))
const robotsOutputPath = fileURLToPath(new URL('../public/robots.txt', import.meta.url))
const sitemapOutputPath = fileURLToPath(new URL('../public/sitemap.xml', import.meta.url))
const siteHomeUrl = new URL('/', SITE_URL).toString()

const declarations = (values) =>
  Object.entries(values)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n')

const themeAliases = {
  ...Object.fromEntries(
    Object.entries(themeTokens.fonts).map(([name, value]) => [`--font-${name}`, value]),
  ),
  ...Object.fromEntries(
    Object.entries(themeTokens.typography).flatMap(([name, value]) => [
      [`--text-${name}`, value.size],
      [`--text-${name}--line-height`, value.lineHeight],
    ]),
  ),
  ...Object.fromEntries(
    Object.entries(themeTokens.colors).map(([name, value]) => [
      `--color-${name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`,
      value,
    ]),
  ),
  ...Object.fromEntries(
    Object.entries(themeTokens.radii).map(([name, value]) => [`--radius-${name}`, value]),
  ),
  ...Object.fromEntries(
    Object.entries(themeTokens.shadows).map(([name, value]) => [
      `--shadow-${name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`,
      value,
    ]),
  ),
}

const sharedSemanticValues = {
  '--chart-1': 'var(--primary)',
  '--chart-2': 'var(--accent)',
  '--chart-3': 'var(--gold)',
  '--chart-4': 'var(--primary-deep)',
  '--chart-5': 'var(--faint)',
  '--sidebar': 'var(--surface)',
  '--sidebar-foreground': 'var(--foreground)',
  '--sidebar-primary': 'var(--primary)',
  '--sidebar-primary-foreground': 'var(--on-primary)',
  '--sidebar-accent': 'var(--surface-2)',
  '--sidebar-accent-foreground': 'var(--foreground)',
  '--sidebar-border': 'var(--line)',
  '--sidebar-ring': 'var(--accent)',
}

const css = `/* Generated by scripts/generate-theme-css.mjs from @nabd/shared. */
@custom-variant dark (&:is([data-theme='dark'] *));

@theme inline {
${declarations(themeAliases)}
}

:root {
${declarations(webThemeValues.global)}
}

:root,
:root[data-mode='classic'] {
${declarations(webThemeValues.modes.classic)}
}

:root[data-mode='modern'] {
${declarations(webThemeValues.modes.modern)}
}

:root,
:root[data-theme='light'] {
${declarations({ ...webThemeValues.themes.light, ...sharedSemanticValues })}
}

:root[data-mode='modern'],
:root[data-mode='modern'][data-theme='light'] {
${declarations(webThemeValues.themes.modernLight)}
}

:root[data-theme='dark'] {
${declarations({ ...webThemeValues.themes.dark, ...sharedSemanticValues })}
}
`

const robots = `User-agent: *
Allow: /
Disallow: /app/

Sitemap: ${new URL('/sitemap.xml', SITE_URL).toString()}
`

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${siteHomeUrl}</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`

await Promise.all([
  writeFile(themeOutputPath, css),
  writeFile(robotsOutputPath, robots),
  writeFile(sitemapOutputPath, sitemap),
])
