// Design tokens mirrored from app/globals.css's @theme block. Values remain CSS-ready so the
// web theme can consume them directly; native configuration can read the same named token map.
export const themeTokens = {
  fonts: {
    sans: 'var(--font-body)',
    body: 'var(--font-body)',
    display: 'var(--font-display)',
    scripture: 'var(--font-scripture)',
  },
  typography: {
    display: { size: '40px', lineHeight: '1.2' },
    title: { size: '24px', lineHeight: '1.2' },
    subtitle: { size: '22px', lineHeight: '1.3' },
    body: { size: '16px', lineHeight: '1.7' },
    small: { size: '13px', lineHeight: '1.5' },
    xsmall: { size: '12px', lineHeight: '1.5' },
    label: { size: '11px', lineHeight: '1.4' },
    scripture: { size: '16px', lineHeight: '2' },
  },
  colors: {
    background: 'var(--background)',
    foreground: 'var(--foreground)',
    card: 'var(--card)',
    cardForeground: 'var(--card-foreground)',
    popover: 'var(--popover)',
    popoverForeground: 'var(--popover-foreground)',
    primary: 'var(--primary)',
    primaryForeground: 'var(--primary-foreground)',
    secondary: 'var(--secondary)',
    secondaryForeground: 'var(--secondary-foreground)',
    muted: 'var(--muted)',
    mutedForeground: 'var(--muted-foreground)',
    accent: 'var(--accent)',
    accentForeground: 'var(--accent-foreground)',
    destructive: 'var(--destructive)',
    border: 'var(--border)',
    input: 'var(--input)',
    ring: 'var(--ring)',
    primaryDeep: 'var(--primary-deep)',
    gold: 'var(--gold)',
    goldSoft: 'var(--gold-soft)',
    faint: 'var(--faint)',
    surface: 'var(--surface)',
    surface2: 'var(--surface-2)',
    line: 'var(--line)',
    onPrimary: 'var(--on-primary)',
    ringTrack: 'var(--ring-track)',
    chart1: 'var(--chart-1)',
    chart2: 'var(--chart-2)',
    chart3: 'var(--chart-3)',
    chart4: 'var(--chart-4)',
    chart5: 'var(--chart-5)',
    sidebar: 'var(--sidebar)',
    sidebarForeground: 'var(--sidebar-foreground)',
    sidebarPrimary: 'var(--sidebar-primary)',
    sidebarPrimaryForeground: 'var(--sidebar-primary-foreground)',
    sidebarAccent: 'var(--sidebar-accent)',
    sidebarAccentForeground: 'var(--sidebar-accent-foreground)',
    sidebarBorder: 'var(--sidebar-border)',
    sidebarRing: 'var(--sidebar-ring)',
  },
  radii: {
    sm: 'calc(var(--radius) * 0.6)',
    md: 'calc(var(--radius) * 0.8)',
    lg: 'var(--radius)',
    xl: 'calc(var(--radius) * 1.4)',
    '2xl': 'calc(var(--radius) * 1.8)',
    icon: 'var(--r-icon)',
    button: 'var(--r-btn)',
    chip: 'var(--r-chip)',
    card: 'var(--r-card)',
    ring: 'var(--r-ring)',
  },
  shadows: {
    card: 'var(--shadow)',
    cardSmall: 'var(--shadow-sm)',
  },
} as const

export type ThemeTokens = typeof themeTokens
