// Design tokens mirrored from app/globals.css's @theme block. Values remain CSS-ready so the
// web theme can consume them directly; native configuration can read the same named token map.
export const themeTokens = {
  fonts: {
    sans: 'var(--font-body)',
    body: 'var(--font-body)',
    display: 'var(--font-display)',
    scripture: 'var(--font-scripture)',
  },
  typography: {
    display: { size: '40px', lineHeight: '1.2' },
    title: { size: '24px', lineHeight: '1.2' },
    subtitle: { size: '22px', lineHeight: '1.3' },
    body: { size: '16px', lineHeight: '1.7' },
    small: { size: '13px', lineHeight: '1.5' },
    xsmall: { size: '12px', lineHeight: '1.5' },
    label: { size: '11px', lineHeight: '1.4' },
    scripture: { size: '16px', lineHeight: '2' },
  },
  colors: {
    background: 'var(--background)',
    foreground: 'var(--foreground)',
    card: 'var(--card)',
    cardForeground: 'var(--card-foreground)',
    popover: 'var(--popover)',
    popoverForeground: 'var(--popover-foreground)',
    primary: 'var(--primary)',
    primaryForeground: 'var(--primary-foreground)',
    secondary: 'var(--secondary)',
    secondaryForeground: 'var(--secondary-foreground)',
    muted: 'var(--muted)',
    mutedForeground: 'var(--muted-foreground)',
    accent: 'var(--accent)',
    accentForeground: 'var(--accent-foreground)',
    destructive: 'var(--destructive)',
    border: 'var(--border)',
    input: 'var(--input)',
    ring: 'var(--ring)',
    primaryDeep: 'var(--primary-deep)',
    gold: 'var(--gold)',
    goldSoft: 'var(--gold-soft)',
    faint: 'var(--faint)',
    surface: 'var(--surface)',
    surface2: 'var(--surface-2)',
    line: 'var(--line)',
    onPrimary: 'var(--on-primary)',
    ringTrack: 'var(--ring-track)',
    chart1: 'var(--chart-1)',
    chart2: 'var(--chart-2)',
    chart3: 'var(--chart-3)',
    chart4: 'var(--chart-4)',
    chart5: 'var(--chart-5)',
    sidebar: 'var(--sidebar)',
    sidebarForeground: 'var(--sidebar-foreground)',
    sidebarPrimary: 'var(--sidebar-primary)',
    sidebarPrimaryForeground: 'var(--sidebar-primary-foreground)',
    sidebarAccent: 'var(--sidebar-accent)',
    sidebarAccentForeground: 'var(--sidebar-accent-foreground)',
    sidebarBorder: 'var(--sidebar-border)',
    sidebarRing: 'var(--sidebar-ring)',
  },
  radii: {
    sm: 'calc(var(--radius) * 0.6)',
    md: 'calc(var(--radius) * 0.8)',
    lg: 'var(--radius)',
    xl: 'calc(var(--radius) * 1.4)',
    '2xl': 'calc(var(--radius) * 1.8)',
    icon: 'var(--r-icon)',
    button: 'var(--r-btn)',
    chip: 'var(--r-chip)',
    card: 'var(--r-card)',
    ring: 'var(--r-ring)',
  },
  shadows: {
    card: 'var(--shadow)',
    cardSmall: 'var(--shadow-sm)',
  },
} as const

export type ThemeTokens = typeof themeTokens

// Concrete values are kept alongside the cross-platform token names so each client can
// generate its own platform representation without duplicating the design-system palette.
export const webThemeValues = {
  global: {
    '--font-body': "'Tajawal', system-ui, sans-serif",
    '--font-scripture': "'Amiri', 'Tajawal', serif",
    '--fw-regular': '400',
    '--fw-medium': '500',
    '--fw-semibold': '600',
    '--fw-bold': '700',
    '--fw-black': '900',
    '--sp-1': '4px',
    '--sp-2': '8px',
    '--sp-3': '12px',
    '--sp-4': '16px',
    '--sp-5': '20px',
    '--sp-6': '24px',
    '--sp-8': '32px',
    '--sp-10': '40px',
    '--sp-12': '48px',
    '--ease': 'cubic-bezier(0.22, 0.61, 0.36, 1)',
    '--dur': '0.22s',
  },
  modes: {
    classic: {
      '--font-display': "'Aref Ruqaa', 'Amiri', serif",
      '--r-icon': '50%',
      '--r-btn': '14px',
      '--r-chip': '22px',
      '--r-card': '16px',
      '--r-ring': '50%',
      '--radius': '14px',
    },
    modern: {
      '--font-display': "'Reem Kufi', 'Tajawal', sans-serif",
      '--r-icon': '12px',
      '--r-btn': '12px',
      '--r-chip': '10px',
      '--r-card': '16px',
      '--r-ring': '22px',
      '--radius': '12px',
    },
  },
  themes: {
    modernLight: {
      '--bg': '#f4f8f7',
      '--muted-foreground': '#4d7875',
    },
    light: {
      '--bg': '#eaf2f0',
      '--surface': '#ffffff',
      '--surface-2': '#eaf2f0',
      '--primary': '#0e5a5a',
      '--primary-deep': '#0e4f52',
      '--accent': '#2fa6a0',
      '--gold': '#c79a3a',
      '--gold-soft': '#fbf3df',
      '--faint': '#9bbebb',
      '--line': 'rgba(16, 48, 47, 0.1)',
      '--on-primary': '#eaf2f0',
      '--ring-track': 'rgba(234, 242, 240, 0.22)',
      '--background': 'var(--bg)',
      '--foreground': '#0e3234',
      '--card': 'var(--surface)',
      '--card-foreground': '#0e3234',
      '--popover': 'var(--surface)',
      '--popover-foreground': '#0e3234',
      '--primary-foreground': 'var(--on-primary)',
      '--secondary': 'var(--surface-2)',
      '--secondary-foreground': '#0e3234',
      '--muted': 'var(--surface-2)',
      '--muted-foreground': '#4a706d',
      '--accent-foreground': '#0e3234',
      '--destructive': 'var(--gold)',
      '--border': 'var(--line)',
      '--input': 'var(--line)',
      '--ring': 'var(--accent)',
      '--shadow': '0 8px 24px rgba(14, 90, 90, 0.1)',
      '--shadow-sm': '0 2px 8px rgba(14, 90, 90, 0.08)',
    },
    dark: {
      '--bg': '#08201f',
      '--surface': '#0e3234',
      '--surface-2': '#103a38',
      '--primary': '#12736f',
      '--primary-deep': '#0e5a5a',
      '--accent': '#3fbdb6',
      '--gold': '#d9ae4e',
      '--gold-soft': '#2a2a18',
      '--faint': '#4e6e6b',
      '--line': 'rgba(234, 242, 240, 0.1)',
      '--on-primary': '#eaf2f0',
      '--ring-track': 'rgba(234, 242, 240, 0.14)',
      '--background': 'var(--bg)',
      '--foreground': '#eaf2f0',
      '--card': 'var(--surface)',
      '--card-foreground': '#eaf2f0',
      '--popover': 'var(--surface)',
      '--popover-foreground': '#eaf2f0',
      '--primary-foreground': 'var(--on-primary)',
      '--secondary': 'var(--surface-2)',
      '--secondary-foreground': '#eaf2f0',
      '--muted': 'var(--surface-2)',
      '--muted-foreground': '#7fa6a3',
      '--accent-foreground': '#08201f',
      '--destructive': 'var(--gold)',
      '--border': 'var(--line)',
      '--input': 'var(--line)',
      '--ring': 'var(--accent)',
      '--shadow': '0 10px 30px rgba(0, 0, 0, 0.35)',
      '--shadow-sm': '0 3px 12px rgba(0, 0, 0, 0.3)',
    },
  },
} as const
