// Regenerates content/adhkar.ts from islambook.com category pages (NBD-23).
//
// Usage:
//   node scripts/scrape-adhkar.mjs                # fetch from the network (slow, ~20s/page)
//   node scripts/scrape-adhkar.mjs --from-dir DIR # parse saved HTML files DIR/cat<ID>.html
//
// The site sits behind Cloudflare and rate-limits aggressively, so network mode paces one
// request every 20 seconds with a browser User-Agent. CI never runs this — the generated
// content is committed and reviewed like any authored file.

import { writeFileSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const CATEGORIES = [
  { id: 1, slug: 'morning', title: 'أذكار الصباح' },
  { id: 2, slug: 'evening', title: 'أذكار المساء' },
  { id: 9, slug: 'after-prayer', title: 'أذكار بعد الصلاة' },
  { id: 11, slug: 'sleep', title: 'أذكار النوم' },
]

const FETCH_DELAY_MS = 20_000
const USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0'
const SOURCE_URL = 'https://www.islambook.com/azkar'

const stripTags = (html) =>
  html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, ' ')
    .trim()

function parseCategory(html, category) {
  // Each dhikr is one .zekr-row: the dhikr text (with an optional subtitle line), a repeat
  // counter, and a "bless" line holding the فضل/source.
  const rows = html.split(/<div class="row zekr-row/).slice(1)
  const items = []
  for (const row of rows) {
    const textMatch = row.match(
      /class="zekr zekr-style[^"]*"[^>]*>([\s\S]*?)<\/div>\s*<div class="text-justify zekrbless|class="zekr zekr-style[^"]*"[^>]*>([\s\S]*?)<\/div>\s*<\/div>\s*<div class="col-b/,
    )
    const rawText = textMatch ? (textMatch[1] ?? textMatch[2]) : null
    if (!rawText) continue

    const subtitleMatch = rawText.match(/<div dir="rtl" class="subtitle">([\s\S]*?)<\/div>/)
    const subtitle = subtitleMatch ? stripTags(subtitleMatch[1]) : ''
    const body = stripTags(rawText.replace(/<div dir="rtl" class="subtitle">[\s\S]*?<\/div>/, ''))
    const text = subtitle ? `${subtitle} ${body}`.trim() : body

    const countMatch = row.match(/zekr-counter[^>]*>\s*([\s\S]*?)<\/div>/)
    const repeat = countMatch ? Number.parseInt(stripTags(countMatch[1]), 10) || 1 : 1

    const virtueMatch = row.match(/class="zekrbless-content">([\s\S]*?)<\/span>/)
    const virtue = virtueMatch ? stripTags(virtueMatch[1]) : undefined

    if (!text) continue
    items.push({ id: `${category.slug}-${items.length + 1}`, text, repeat, virtue })
  }
  return items
}

async function loadHtml(category, fromDir) {
  if (fromDir) {
    return readFileSync(join(fromDir, `cat${category.id}.html`), 'utf8')
  }
  const url = `${SOURCE_URL}/${category.id}/x`
  const res = await fetch(url, {
    headers: { 'User-Agent': USER_AGENT, Accept: 'text/html' },
  })
  if (!res.ok) throw new Error(`${url} -> ${res.status}`)
  return res.text()
}

const escape = (s) => s.replaceAll('\\', '\\\\').replaceAll("'", "\\'")

async function main() {
  const fromDirIdx = process.argv.indexOf('--from-dir')
  const fromDir = fromDirIdx > -1 ? process.argv[fromDirIdx + 1] : null

  const categories = []
  for (const category of CATEGORIES) {
    const html = await loadHtml(category, fromDir)
    const items = parseCategory(html, category)
    if (items.length === 0)
      throw new Error(`no items parsed for ${category.slug} — layout changed?`)
    categories.push({ ...category, items })
    console.log(`${category.slug}: ${items.length} adhkar`)
    if (!fromDir) await new Promise((resolve) => setTimeout(resolve, FETCH_DELAY_MS))
  }

  const lines = []
  lines.push('// GENERATED by scripts/scrape-adhkar.mjs — do not hand-edit item texts here.')
  lines.push(
    `// Source: ${SOURCE_URL} (islambook.com), fetched ${new Date().toISOString().slice(0, 10)}.`,
  )
  lines.push(
    '// The adhkar reference library (NBD-12, expanded NBD-23): browsable independent of the',
  )
  lines.push("// user's wird. Zero runtime imports per the /content boundary (architecture.md).")
  lines.push('')
  lines.push("import { DAILY_ADHKAR_CATEGORY } from './daily-adhkar'")
  lines.push('')
  lines.push('export type Dhikr = {')
  lines.push('  id: string')
  lines.push('  text: string')
  lines.push('  // Recommended repetitions per the narration. 1 when the dhikr is said once.')
  lines.push('  repeat: number')
  lines.push('  // فضل الذكر / its source, as carried by the reference.')
  lines.push('  virtue?: string')
  lines.push('}')
  lines.push('')
  lines.push('export type AdhkarCategory = {')
  lines.push('  id: string')
  lines.push('  title: string')
  lines.push('  items: Dhikr[]')
  lines.push('}')
  lines.push('')
  lines.push('export const ADHKAR_LIBRARY: AdhkarCategory[] = [')
  for (const category of categories) {
    lines.push('  {')
    lines.push(`    id: '${category.slug}',`)
    lines.push(`    title: '${category.title}',`)
    lines.push('    items: [')
    for (const item of category.items) {
      lines.push('      {')
      lines.push(`        id: '${item.id}',`)
      lines.push(`        text: '${escape(item.text)}',`)
      lines.push(`        repeat: ${item.repeat},`)
      if (item.virtue) lines.push(`        virtue: '${escape(item.virtue)}',`)
      lines.push('      },')
    }
    lines.push('    ],')
    lines.push('  },')
  }
  lines.push('  DAILY_ADHKAR_CATEGORY,')
  lines.push(']')
  lines.push('')

  const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'content', 'adhkar.ts')
  writeFileSync(outPath, lines.join('\n'))
  console.log(`wrote ${outPath}`)
}

await main()
